services:
# ElasticSearch settings
  elasticsearch:
    build: .
    # image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    hostname: elasticsearch
    environment:
    # cluster settings
      - node.name=es01
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node

    # security settings
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=admin@12345
      
    # memory settings
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

      - network.host=0.0.0.0

      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"    # REST API
      - "9300:9300"    # 節點間要通訊，單機雖用不到但仍需保留
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
      - es_plugins:/usr/share/elasticsearch/plugins
# Linux 實機長需要; Mac/Win 通常不用更動
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 
        soft: 262144
        hard: 262144
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    restart: unless-stopped

    networks:
      - elastic

# kibana settings
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    hostname: kibana
    depends_on: 
    - elasticsearch
    environment:
    # connection settings
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana123

    # kibana server settings
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601

    # language settings
      - I18N_LOCALE=zh-TW
      - I18N_DEFAULTLOCALE=zh-TW
      - KIBANA_DEFAULTAPPID=home
    ports:
    - "5601:5601"      #kibana Web
    volumes:
      - kibana_data:/usr/share/kibana/data

     # 健康檢查
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    restart: unless-stopped
    networks:
      - elastic
  
volumes:
  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/elasticsearch
  es_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs/elasticsearch
  es_plugins:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./plugins/elasticsearch
  kibana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/kibana

networks:
  elastic:
    driver: bridge
