services:
# ElasticSearch settings
  elasticsearch:
    build: .
    container_name: es01
    hostname: es01
    environment:
    # cluster settings
      - node.name=es01
      - cluster.name=elasticsearch-cluster
      - discovery.type=single-node

    # security settings
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=admin@12345
      
    # memory settings
      - ES_JAVA_OPTS=-Xms1g -Xmx1g

      - network.host=0.0.0.0

      - bootstrap.memory_lock=true
    ports:
      - "9200:9200"    # REST API
      - "9300:9300"    # 節點間要通訊，單機雖用不到但仍需保留
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - es_logs:/usr/share/elasticsearch/logs
      # - es_plugins:/usr/share/elasticsearch/plugins
      # - ./config/analysis-ik:/usr/share/elasticsearch/config/analysis-ik:ro
      - ./data/import:/data/import:rw
# Linux 實機長需要; Mac/Win 通常不用更動
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile: 
        soft: 262144
        hard: 262144
    
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

    restart: unless-stopped

    networks:
      - elastic

# kibana settings
  kibana:
    image: docker.elastic.co/kibana/kibana:8.15.1
    container_name: kibana
    hostname: kibana
    depends_on: 
    - elasticsearch
    environment:
    # connection settings
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana123

    # kibana server settings
      - SERVER_NAME=kibana
      - SERVER_HOST=0.0.0.0
      - SERVER_PORT=5601

    # language settings
      - I18N_LOCALE=zh-TW
      - I18N_DEFAULTLOCALE=zh-TW
      - KIBANA_DEFAULTAPPID=home
    ports:
      - "5601:5601"      #kibana Web
    volumes:
      - kibana_data:/usr/share/kibana/data

     # 健康檢查
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5601/api/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 120s
    
    restart: unless-stopped
    networks:
      - elastic


# 新增：自動檔案處理服務
  # 升級版資料轉換器
  data-transformer:
    image: python:3.11-slim
    container_name: data-transformer
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=admin@12345
      - PYTHONPATH=/app
    volumes:
      - ./data/import:/data/import:rw
      - ./scripts:/app:rw
      - ./data/state:/app/state:rw  # 狀態檔目錄
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir opencc-python-reimplemented requests pandas pymysql psycopg2-binary &&
        python unified_config.py --mode daemon --config /app/state/transformer_config.json
      "
    restart: unless-stopped
    networks:
      - elastic

  # Hybrid Search API
  search-api:
    image: python:3.11-slim
    container_name: search-api
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - ELASTICSEARCH_USER=elastic
      - ELASTICSEARCH_PASSWORD=admin@12345
      - EMBEDDING_API_URL=  # 可選：向量化服務URL
    ports:
      - "8000:8000"
    volumes:
      - ./scripts:/app:ro
    working_dir: /app
    command: >
      bash -c "
        pip install --no-cache-dir fastapi uvicorn aiohttp numpy &&
        python hybrid_search_api.py
      "
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - elastic

  # 可選：向量化服務 (使用開源模型)
  embedding-service:
    image: python:3.11-slim
    container_name: embedding-service
    ports:
      - "8001:8001"
    volumes:
      - ./models:/models:ro  # 模型檔案目錄
    command: >
      bash -c "
        pip install --no-cache-dir fastapi uvicorn sentence-transformers torch &&
        python -c \"
        from fastapi import FastAPI
        from sentence_transformers import SentenceTransformer
        import uvicorn
        from pydantic import BaseModel

        app = FastAPI()
        # 使用中文優化的模型
        model = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')

        class TextRequest(BaseModel):
        text: str

        @app.post('/embed')
        async def embed_text(request: TextRequest):
        embedding = model.encode(request.text).tolist()
        return {'embedding': embedding}

        @app.get('/health')
        async def health():
        return {'status': 'healthy'}

        if __name__ == '__main__':
        uvicorn.run(app, host='0.0.0.0', port=8001)
            \"
        "
    restart: unless-stopped
    networks:
      - elastic
    profiles:
      - vector  # 使用 docker-compose --profile vector up 啟動

  
volumes:
  es_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/elasticsearch
  es_logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./logs/elasticsearch
  # es_plugins:
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./plugins/elasticsearch
  kibana_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data/kibana

networks:
  elastic:
    driver: bridge
