# Elasticsearch 配置文件
cluster.name: elasticsearch-cluster
node.name: es01
network.host: 0.0.0.0

# 路徑配置
path.data: /usr/share/elasticsearch/data
path.logs: /usr/share/elasticsearch/logs

# 安全配置
xpack.security.enabled: true
xpack.security.enrollment.enabled: true
xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# 監控配置
xpack.monitoring.collection.enabled: true

# IK 分詞器預設配置
index.analysis.analyzer.default.type: ik_max_word
